
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import ReduxProvider from "@/providers/ReduxProvider";
import { ToastContainer } from "react-toastify";
import SessionProviders from "@/providers/SessionProvider";
import 'aos/dist/aos.css'; 
import Footer from "@/shared/Footer";
import SmonthScrollingProvider from "@/providers/SmonthScrollingProvider";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className=''
      >



      <SessionProviders>
     <ReduxProvider>
    <ToastContainer/>
         <Navbar/>\
         
{/*          
<SmonthScrollingProvider> */}
         <div className="min-h-screen bg-gray-900">
                  {children}
         </div>
     
{/* </SmonthScrollingProvider> */}
        <Footer/>

     
   </ReduxProvider>
  
</SessionProviders>














      </body>
    </html>
  );
}
