import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import ReduxProvider from "@/providers/ReduxProvider";
import { ToastContainer } from "react-toastify";
import SessionProviders from "@/providers/SessionProvider";
import 'aos/dist/aos.css'; 
import Footer from "@/shared/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=''
      >

<SessionProviders>
     <ReduxProvider>
    <ToastContainer/>
         <Navbar/>\
         <div className="min-h-screen">
                  {children}
         </div>

        <Footer/>
   </ReduxProvider>
</SessionProviders>
      </body>
    </html>
  );
}
